version: "3"

networks:
  traefik:
    external: true
  

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=movie-pastel-good-nice
      - DATABASE_USER=teslamate
      - DATABASE_PASS=movie-pastel-good-nice
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all
    networks:
      - traefik
      - default

  database:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=movie-pastel-good-nice
      - POSTGRES_DB=teslamate
    ports:
      - 5432:5432
    volumes:
      - teslamate-db:/var/lib/postgresql/data

#  grafana:
#    image: teslamate/grafana:latest
#    restart: always
#    environment:
#      - DATABASE_USER=teslamate
#      - DATABASE_PASS=movie-pastel-good-nice
#      - DATABASE_NAME=teslamate
#      - DATABASE_HOST=database
#    ports:
#      - 3000:3000
#    volumes:
#      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
