services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ./autobrr/config:/config
    ports:
      - "7474:7474"
    networks:
      - traefik

  deluge:
    container_name: deluge
    image: binhex/arch-delugevpn
    cap_add:
      - NET_ADMIN
    labels:
      - "traefik.http.services.deluge-service.loadbalancer.server.port=8112"
    ports:
      - "8112:8112"
      - "8118:8118"
      - "9118:9118"
      - "58846:58846"
      - "58946:58946"
      - "58946:58946/udp"
    volumes:
      - ./deluge/config:/config
      - /media/plex:/data
      - ./seeding:/seeding
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - PUID=${DELUGE_PUID}
      - PGID=${DELUGE_PGID}
      - UMASK=000
      - VPN_ENABLED=${VPN_ENABLED}
      - VPN_USER=${VPN_USER}
      - VPN_PASS=${VPN_PASS}
      - VPN_PROV=${VPN_PROV}
      - VPN_CLIENT=${VPN_CLIENT}
      - STRICT_PORT_FORWARD=yes
      - VPN_INPUT_PORTS=${VPN_INPUT_PORTS}
      - VPN_OUTPUT_PORTS=${VPN_OUTPUT_PORTS}
      - LAN_NETWORK=${LAN_NETWORK}
      - NAME_SERVERS=${NAME_SERVERS:-1.1.1.1,1.0.0.1}
      - ENABLE_PRIVOXY=yes
      - ENABLE_SOCKS=${ENABLE_SOCKS:-yes}
      - SOCKS_USER=${SOCKS_USER}
      - SOCKS_PASS=${SOCKS_PASS}
      - DELUGE_ENABLE_WEBUI_PASSWORD=yes
      - ENABLE_STARTUP_SCRIPTS=no
      - USERSPACE_WIREGUARD=no
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - DEBUG=false
    networks:
      - traefik
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./radarr/config:/config
      - /media/plex:/data
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - traefik

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr/config:/config
      - /media/plex:/data
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - traefik

  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./readarr/config:/config
      - /media/plex:/data
    ports:
      - "8787:8787" # Readarr default web UI port
    networks:
      - traefik

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID} # From .env
      - PGID=${PGID} # From .env
      - TZ=${TZ}     # From .env
    volumes:
      - ./overseerr/config:/config # Config stored relative to compose file in 'arr/overseerr/config'
    ports:
      - "5055:5055" # Overseerr default web UI port
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.http.routers.overseerr-router.rule=Host(`overseer.fwd.ryanmahan.dev`)"
      - "traefik.http.middlewares.test-ipallowlist.ipallowlist.sourcerange=0.0.0.0/0"
      - "traefik.http.routers.overseerr-router.entrypoints=websecure"
      - "traefik.http.routers.overseerr-router.tls.certresolver=fwd-letsencrypt"
  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - ./jackett/config:/config
      - /downloads:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped
    networks:
      - traefik

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest # Or :develop for newer features/fixes
    restart: unless-stopped
    environment:
      - PUID=${PUID} # From .env
      - PGID=${PGID} # From .env
      - TZ=${TZ}     # From .env
    volumes:
      - ./prowlarr/config:/config # Config stored relative to compose file
    ports:
      - "9696:9696" # Prowlarr default port
    networks:
      - traefik

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

networks:
  traefik:
    external: true
